name: Jest Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  jest-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jest-report
          path: jest-report/
          retention-days: 30
